name: Publish Docker image
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - github_actions
      - clang
      - master
  release:
    types: [published]
jobs:
  buildr_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Env Variables
        id: set-env-vars
        shell: bash
        run: |
          export GIT_BRANCH=${GITHUB_REF#refs/heads/}
          export DOCKER_TAG=${GIT_BRANCH//\//'-'}
          echo "::set-output name=DOCKER_TAG::$DOCKER_TAG"

          export DOCKER_REPO="fibjs/build-env"
          echo "::set-output name=DOCKER_REPO::$DOCKER_REPO"
          
          export DOCKER_REPO_WITH_TAG="$DOCKER_REPO:$DOCKER_TAG"
          echo "::set-output name=DOCKER_REPO_WITH_TAG::$DOCKER_REPO_WITH_TAG"
      - name: Build
        shell: bash
        run: |
          rm -rf ./arm_root_fs
          tar -zxf ./arm_root_fs.tar.gz

          rm -rf ./arm64_root_fs
          tar -zxf ./arm64_root_fs.tar.gz

          docker build .
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ steps.set-env-vars.outputs.DOCKER_REPO }}
          tag_with_ref: true
          # tags: ${{ steps.set-env-vars.outputs.DOCKER_TAG  }}
          # push: true